SQL packaging
cantarus/PolyDeploy pull request #20
Opened 2018-03-28 20:59 UTC by bdukes

The 0.6.0 package creates a `SqlDataProviders` folder in the root of the website
with all of the PolyDeploy SQL scripts.  This PR updates the packaging to put them in `DesktopModules/Cantarus/PolyDeploy/SqlDataProviders`

2018-05-08 15:00 UTC, can-anierzad commented
Thanks for bringing this to our attention Brian, I had absolutely no idea that PolyDeploy was dropping its `SqlDataProviders` folder at the root of the website.

I've been trying to test this today but unfortunately I receive an installation error. I did a little trial and error and found that by replacing the `/` with `\` in the `basePath` that everything runs smoothly and as expected.

Have you encountered anything similar?

2018-05-08 15:02 UTC, can-anierzad commented on PolyDeploy/PolyDeploy.dnn
> +            <basePath>DesktopModules/Cantarus/PolyDeploy/</basePath>
I can only seem to get the installation to succeed if I change this value to `DesktopModules\Cantarus\PolyDeploy\`.

2018-05-08 17:15 UTC, bdukes commented
Weird, I don't think I've ever run into the slashes making a difference in a `.dnn` file, but if it works the other way, that sounds good to me

2018-05-09 11:36 UTC, can-anierzad commented
Yeah I thought it was weird too.

I did a little more digging and I think I've found the problem. It's not actually to do with whether forward or backward slashes are used although the use of backward slashes will mitigate the issue seemingly. The problem is actually that if the `basePath` features a trailing forward slash DNN will replace it with two back slashes in addition to the two back slashes it has already appended because it thought there was no trailing back slash.

I've opened an issue with DNN dnnsoftware/Dnn.Platform#2059. Not critical but might avoid others tracing the same problem through the source.

We'll just omit the trailing forward slash.

2018-05-09 11:37 UTC, ghost requested changes

2018-05-09 11:37 UTC, can-anierzad commented on PolyDeploy/PolyDeploy.dnn
> +            <basePath>DesktopModules/Cantarus/PolyDeploy/</basePath>
Please can you remove the trailing slash from this path.

2018-05-09 12:54 UTC, bdukes commented
@can-anierzad thanks for tracking that down.  I've made the requested change.  Let me know if there's anything else.

2018-05-09 14:04 UTC, ghost approved these changes

2018-05-09 14:13 UTC, merged